fix: fix flinksql create table grammar, add test
DTStack/dt-sql-parser pull request #65
Opened 2022-12-22 03:50 UTC by nankaNULL

#### issue
issue: [#64](https://github.com/DTStack/dt-sql-parser/issues/64)

#### 解决问题
1. 支持 Metadata Columns 语法
2. 支持 Computed Columns 语法
3. 支持 PRIMARY KEY 的 NOT ENFORCED
4. 完善 LIKE 语法
5. 新增以上语法的单测

#### 其他优化
1. 支持 TIMESTAMP_LTZ 类型
#### 参考
https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/dev/table/sql/create/#create-table

2022-12-23 01:54 UTC, wewoor reviewed
已合并 dataType 分支

2022-12-27 01:57 UTC, wewoor approved these changes
+1

2022-12-27 05:34 UTC, wewoor requested changes
解决下冲突

2022-12-28 06:10 UTC, wewoor approved these changes
+1

2022-12-28 06:12 UTC, nankaNULL commented
冲突已解，base分支改为 master 了

2022-12-28 06:20 UTC, merged